### PR TITLE
mkdir function added

### PR DESCRIPTION
**Pull request by dynamo63**
:blush: Hi and **Sorry for the inconvenience**, I notice there was no method to create a directory so I added my mkdir key :wink: !

### CODE REVIEW

**Comment by codebynumbers** [comment]
No need to apologize. Looks good, should also add an example to the README and a test wouldn't hurt either.

**Comment by dynamo63** [comment]
:blush: I made **the desired changes**

**Comment by dynamo63** [comment]
Please :yum:  , Can you label this PR **hacktoberfest-accepted**? is very important for me !

**Comment by codebynumbers** [comment]
Sure thing.

**Pull request merged**
